name: docker-workflow
on:
    push:
jobs:
    docker-login:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              
            - name: Docker Login
              uses: docker/login-action@v4.1.0
              with:
                username: ${{ vars.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Github registry Login
              uses: docker/login-action@v4.1.0
              with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GITHUB_TOKEN }}
          
            - name: Docker Build for testing
              uses: docker/build-push-action@v7
              with:
                context: .
                push: false
                tags: ${{ vars.DOCKER_USERNAME}}/solar-system:latest
            
            - name: Test script
              run: |
                export MONGO_USERNAME=${{ vars.MONGO_USERNAME }}
                export MONGO_URI=${{ vars.MONGO_URI }}
                export MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}
                export IMAGE=${{ vars.DOCKER_USERNAME}}/solar-system:latest
                chmod +x containerRunScript.sh
                ./containerRunScript.sh
            - name: Push image - github container & Docker hub
              uses: docker/build-push-action@v7
              with:
                push: true
                context: .
                tags: |
                     ${{ vars.DOCKER_USERNAME}}/solar-system:latest
                     ghcr.io/${{ github.repository_owner}}/solar-system:latest
