## This is to test different nodejs versions across different OS platform - Ex - Diff apps testing
## across different OS paltform

name: Solar System Workflow with OS & node.js matrix

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
env:
    MONGO_URI: mongodb+srv://cluster0.b8qyhhx.mongodb.net/solarsystem
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD}}
jobs:
    unit-testing:
        name: Unit Testing
        strategy:
            matrix:
                nodejs_version: [20, 22, 24]
                Operating_system: [ubuntu-latest, macos-latest]
                exclude:
                    - nodejs_version: 20
                      operating_system: macos-latest
        runs-on: ${{matrix.operating_system}}
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version - ${{matrix.nodejs_version}}
          uses: actions/setup-node@v3
          with:
            node-version: ${{matrix.nodejs_version}}        # Installtions of node.js version 
    
        - name: Install Dependencies
          run: npm install          # Installtions of nde.js dependencies
    
        - name: Unit Testing        # testing nodejs with npm test
          run: npm test
          
        - name: Archive Test Result  # Uploading artifacts
          uses: actions/upload-artifact@v4
          with:
            name: Mocha-Test-Result
            path: test-results.xml