name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
env:
  MONGO_URI: ${{ vars.MONGO_URI }}
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
    
jobs:
    unit-testing:
        name: Unit Testing job
        # if: github.ref_name == 'git/ref/main'
        env:
          MONGO_URI: mongodb://localhost:27017/superData
          MONGO_USERNAME: non-prod-user
          MONGO_PASSWORD: non-prod-password
        services:
          mongo-db:
            image: siddharth67/mongo-db:non-prod
            ports:
              - 27017:27017
        strategy:
          matrix:
            node-version: [24]
            os: [ubuntu-latest]
            # exclude:
            #   - node-version: 20
            #     os: ubuntu-latest
        runs-on: ${{ matrix.os }}
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}

        # - name: Cache npm packages/dependencies
        #   uses: actions/cache@v5.0.4
        #   with:
        #     path: node_modules
        #     key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
            
    
        # - name: Install Dependencies
        #   run: npm install

        - name: "Composite action- Cache & Install NPM dependencies"
          uses: ./.github/custom-actions/npm-actions
          with: 
            path-of-folder: node_modules
    
        - name: Unit Testing
          id: unit-testing-step
          run: npm test
          
        - name: Archive Test Result.
          # if: failure() || success() || always() && (steps.unit-testing-step.outcome == 'success')
          uses: actions/upload-artifact@v6
          with:
            name: Mocha-Test-Result-${{matrix.node-version}}-${{matrix.os}}
            path: test-results.xml

    code-coverage:
      name: Code Coverage
      runs-on: ubuntu-latest
      env:
          MONGO_URI: mongodb://mongo:27017/superData
          MONGO_USERNAME: non-prod-user
          MONGO_PASSWORD: non-prod-password
      services:
        mongo-db:
          image: siddharth67/mongo-db:non-prod
          ports:
            - 27017:27017
          options:
            --name mongo
      container:
        image: node:18
      steps:
          - name: Checkout repo
            uses: actions/checkout@v4

          # - name: Install node
          #   uses: actions/setup-node@v3
          #   with:
          #     node-version: 24

          # - name: Create cache for node Dependencies
          #   uses: actions/cache@v5.0.4
          #   with:
          #     path: node_modules
          #     key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}

          # - name: Install dependencies
          #   run: npm install

          - name: "Composite action- Cache & Install NPM dependencies"
            uses: ./.github/custom-actions/npm-actions
            with: 
              path-of-folder: node_modules

          - name: Code coverage step
            run: |
              npm run coverage
            continue-on-error: true
          
          - name: Artifacting code coverate results
            uses: actions/upload-artifact@v6
            with:
              name: code-coverage-result
              path: coverage
              retention-days: 5

    aws-s3-upload:
      runs-on: ubuntu-latest
      if: github.ref_name == 'main'
      needs: [code-coverage]
      continue-on-error: true
      steps:
        - name: download test artifact
          uses: actions/download-artifact@v6
          with:
            name: Mocha-Test-Result-24-ubuntu-latest
            path: ./Mocha-Test-Result-24-ubuntu-latest
            

        - name: download code coverage artifact
          uses: actions/download-artifact@v6
          with:
            name: code-coverage-result
            path: ./code-coverage-result

        - name: display the file 
          run: ls -l
        
        - name: Moviing artifacts into a single directory into reports
          run: |
            mkdir reports-${{ github.sha }}
            mv Mocha-Test-Result-24-ubuntu-latest reports-${{ github.sha }}/
            mv code-coverage-result reports-${{ github.sha }}/

            ls -l
            ls reports-${{ github.sha }}/

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v6.1.0
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

        - name: Upload to AWS S3
          run: |
               aws s3 cp reports-${{ github.sha }} s3://${{ secrets.AWS_BUCKET}}/reports-${{ github.sha }} --recursive

    Docker-containerization:
      runs-on: ubuntu-latest
      needs: [unit-testing , code-coverage]
      if: github.ref_name == 'main'
      steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              
            - name: Docker Login
              uses: docker/login-action@v4.1.0
              with:
                username: ${{ vars.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            # - name: Github registry Login
            #   uses: docker/login-action@v4.1.0
            #   with:
            #     registry: ghcr.io
            #     username: ${{ github.repository_owner }}
            #     password: ${{ secrets.GITHUB_TOKEN }}
          
            - name: Docker Build for testing
              uses: docker/build-push-action@v7
              with:
                context: .
                push: false
                tags: ${{ vars.DOCKER_USERNAME}}/solar-system:latest
            
            - name: Test script
              run: |
                export MONGO_USERNAME=${{ vars.MONGO_USERNAME }}
                export MONGO_URI=${{ vars.MONGO_URI }}
                export MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}
                export IMAGE=${{ vars.DOCKER_USERNAME}}/solar-system:latest
                chmod +x containerRunScript.sh
                ./containerRunScript.sh
            - name: Push image - github container & Docker hub
              uses: docker/build-push-action@v7
              with:
                push: true
                context: .
                tags: |
                     ${{ vars.DOCKER_USERNAME}}/solar-system:latest
                    #  ghcr.io/${{ github.repository_owner}}/solar-system:latest

    Slack-notification:
      if: always()
      runs-on: ubuntu-latest
      needs: [unit-testing , code-coverage]
      continue-on-error: true
      steps:
        - name: github checkout
          uses: actions/checkout@v6
        
        - name: Slack notification
          uses: rtCamp/action-slack-notify@v2
          env:
            SLACK_CHANNEL: ${{ vars.SLACK_CHANNEL }}
            SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
            SLACK_ICON: https://github.com/rtCamp.png?size=48
            SLACK_MESSAGE: "github action completed. triggered by - ${{ github.repository_owner }} , Branch - ${{ github.ref_name }}"
            SLACK_TITLE: 'Action Status'
            SLACK_USERNAME: githubBot
            SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

